# Generated by Django 5.0 on 2024-11-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_management",
            "0002_project_projectmilestone_task_taskattachment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmilestone",
            name="project",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="user",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectMilestone",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskAttachment",
        ),
        migrations.DeleteModel(
            name="TaskComment",
        ),
    ]
