# Generated by Django 5.0 on 2024-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0003_remove_projectmilestone_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_verification_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mobile_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mobile_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
