# Generated by Django 5.0 on 2024-12-06 08:05

import django.db.models.deletion
import task_management.models.task_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0003_tasknotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TaskFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=task_management.models.task_models.get_file_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("file_type", models.CharField(max_length=10)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="task_management.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
