# Generated by Django 5.0 on 2024-11-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0005_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
