# Generated by Django 5.0 on 2024-12-07 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0005_taskcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyKeywordSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_type", models.CharField(max_length=20)),
                ("keyword", models.CharField(max_length=50)),
                ("selection_date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name_plural": "Daily Keyword Selections",
                "ordering": ["selection_date", "profile_type"],
            },
        ),
    ]
