# Generated by Django 5.0 on 2024-11-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_management", "0007_dailyarticleselection_profilekeywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("yet_to_start", "Yet to Start"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="yet_to_start",
                max_length=20,
            ),
        ),
    ]
