# Generated by Django 5.0 on 2024-12-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0007_task_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="team_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
