# Generated by Django 5.0 on 2024-11-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0008_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file_uploaded_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_file",
            field=models.FileField(
                blank=True, null=True, upload_to="task_files/%Y/%m/%d/"
            ),
        ),
    ]
