# Generated by Django 5.0 on 2024-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0008_customuser_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="team_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
