# Generated by Django 5.0 on 2024-12-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0009_task_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="team_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
