# Generated by Django 5.0 on 2024-11-28 17:59

import django.db.models.deletion
import task_management.models.task_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0009_task_file_uploaded_at_task_task_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=task_management.models.task_models.user_directory_path,
            ),
        ),
        migrations.CreateModel(
            name="TaskFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=task_management.models.task_models.user_directory_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="task_management.task",
                    ),
                ),
            ],
        ),
    ]
