# Generated by Django 5.0 on 2024-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0011_remove_task_file_uploaded_at_remove_task_task_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
