# Generated by Django 5.0 on 2024-11-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0012_alter_task_end_date_alter_task_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyarticleselection",
            name="highlight",
            field=models.TextField(blank=True, null=True),
        ),
    ]
