# Generated by Django 5.0 on 2024-11-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0014_taskcategory_task_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskcategory",
            options={},
        ),
    ]
